---
title: Fra Veggli til Tøyenparken
subtitle: Festivalsommerens mange ansikt og sprengte trommehinner
css: artikler.css
---
09.08.2025

[Monument](mnmt.no) og [Øyafestivalen](https://www.oyafestivalen.no/) faller begge inn under begrepet musikkfestival. Til tross for dette er det store forskjeller mellom festivalene: en  av de er i skogen og den den andre er i byen. I tillegg har Øya fått Palestinaaktivistene på nakken, noe Monument har til gode å oppleve. 

Billettprisen for en langhelg i Vegglis Søre Risteigen gård strekker ikke lenger enn én dag på Øyafestivalen: om lag 1700 NOK. Dette til tross for at Monument ble utsolgt et i god tid før sommeren var i gang. 

I Veggli strekker 1700 kroner seg langt. Ikke bare får man muligheten til å gå barbeint i gresset mens noen av verdens fremste DJer spiller dunkemusikk: man får danse side om side med en hel bygd som støtter en nisje innenfor norske musikkfestivaler - enten de har kommet seg inn på festivalen eller lytter nysgjerrig mens de går forbi.

Inntrykket vi satt igjen med etter en langhelg i Veggli var det sterke samholdet. Ikke bare de uttallige klemmene man får være vitne til om man stikker innom festivalen, men samholdet i bygda. Hverken det eldre ekteparet som drakk kaffe på kroa, naboen vi møtte på vei til badeplassen i Numedalslågen eller hyttefolket hadde noe negativt å si om festivalen (sett bort ifra [debatten om rusmisbruk på festivalen](https://www.laagendalsposten.no/onsker-vi-a-legge-til-rette-eller-bedre-tilgangen-pa-ulovlig-rusmidler-i-var-kommune/o/5-64-1454419)).

**Men hva er vår kjære festivalsommers røde tråd?**

Enten man har betalt dyre dommer for å se favorittbandet sitt spille i en av storbyenes parker, vippset en hundrelapp eller to til ildjseler som sniker med seg lydanlegg inn i Oslo sine skoger eller om man er med på en bygdefest med lasershow og en bass som dundrer er likheten påfallende:

Hørselvern er forbeholdt de med god planleggingsevne, de som leter og de som er villige til å kaste en halv løk på en lett tilgjengelig festivalbod.

Festivalene titter nøye gjennom sekker og vesker, men når skal jeg få et par ørepropper i neven?


